/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_Driver_Automatic.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "PCDriver_PC_Automatic.h"
#include "resources_CarMessages_Automatic.h"
#include "resources_DriverMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'myCar_Driver'
 * data set:.....................................'MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT myCar_Driver_CAL_MEM = {
   /* struct element:'myCar_Driver_CAL_MEM.v_target' (modeled as:'v_target.myCar_Driver') */
   3000U,
   /* struct element:'myCar_Driver_CAL_MEM.Lane_Change_left' (modeled as:'Lane_Change_left.myCar_Driver') */
   false,
   /* struct element:'myCar_Driver_CAL_MEM.Lane_Change_right' (modeled as:'Lane_Change_right.myCar_Driver') */
   false,
   /* substruct: myCar_Driver_CAL_MEM.Driver_Tempo_instance (modeled as:'Driver_Tempo_instance.myCar_Driver') */
   {
      /* struct element:'myCar_Driver_CAL_MEM.Driver_Tempo_instance.power' (modeled as:'power.Driver_Tempo_instance.myCar_Driver') */
      30.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'myCar_Driver'
 * data set:.....................................'MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_Driver_Automatic_RAM_SUBSTRUCT myCar_Driver_RAM = {
   /* struct element:'myCar_Driver_RAM.distance_next_Obstacle' (modeled as:'distance_next_Obstacle.myCar_Driver') */
   0.0F,
   /* struct element:'myCar_Driver_RAM.min_dist_to_obstacle' (modeled as:'min_dist_to_obstacle.myCar_Driver') */
   0.0F,
   /* substruct: myCar_Driver_RAM.Driver_Tempo_instance (modeled as:'Driver_Tempo_instance.myCar_Driver') */
   {
      /* struct element:'myCar_Driver_RAM.Driver_Tempo_instance.brake_out' (modeled as:'brake_out.Driver_Tempo_instance.myCar_Driver') */
      0.0F,
      /* struct element:'myCar_Driver_RAM.Driver_Tempo_instance.power_out' (modeled as:'power_out.Driver_Tempo_instance.myCar_Driver') */
      0.0F
   },
   /* substruct: myCar_Driver_RAM.Obstacles_instance (modeled as:'Obstacles_instance.myCar_Driver') */
   {
      /* struct element:'myCar_Driver_RAM.Obstacles_instance.min_dist_to_obst' (modeled as:'min_dist_to_obst.Obstacles_instance.myCar_Driver') */
      0.0F,
      /* struct element:'myCar_Driver_RAM.Obstacles_instance.max_count_line' (modeled as:'max_count_line.Obstacles_instance.myCar_Driver') */
      {
         12U,
         {
            5.0F, 10.0F, 15.0F, 20.0F, 25.0F, 30.0F, 35.0F, 40.0F, 45.0F, 50.0F, 55.0F,
            60.0F
         },
         {
            706.0F, 419.0F, 236.0F, 177.0F, 149.0F, 128.0F, 116.0F, 105.0F, 97.0F, 90.0F,
            84.0F, 80.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'myCar_Driver'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'myCar_Driver'
 * data set:.....................................'MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct myCar_Driver_Automatic myCar_Driver = {
   /* substruct: myCar_Driver.Driver_Tempo_instance (modeled as:'Driver_Tempo_instance.myCar_Driver') */
   {
      /* type descriptor pointer 'myCar_Driver_Tempo_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &myCar_Driver_CAL_MEM.Driver_Tempo_instance,
      /* type descriptor pointer 'myCar_Driver_Tempo_Automatic_RAM' for memory class substruct for 'RAM' */
      &myCar_Driver_RAM.Driver_Tempo_instance
   },
   /* substruct: myCar_Driver.Obstacles_instance (modeled as:'Obstacles_instance.myCar_Driver') */
   {
      /* type descriptor pointer 'myCar_Obstacles_Automatic_RAM' for memory class substruct for 'RAM' */
      &myCar_Driver_RAM.Obstacles_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'myCar_Driver'
 ******************************************************************************/





#define distance_next_Obstacle_VAL (myCar_Driver_RAM.distance_next_Obstacle)
#define Driver_Tempo_instance_REF (&(myCar_Driver.Driver_Tempo_instance))
#define Lane_Change_left_VAL (myCar_Driver_CAL_MEM.Lane_Change_left)
#define Lane_Change_right_VAL (myCar_Driver_CAL_MEM.Lane_Change_right)
#define min_dist_to_obstacle_VAL (myCar_Driver_RAM.min_dist_to_obstacle)
#define Obstacles_instance_REF (&(myCar_Driver.Obstacles_instance))
#define v_target_VAL (myCar_Driver_CAL_MEM.v_target)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void myCar_Driver_Automatic_calc (void)
{
   /* define local message copies */
   float32 resources_CarMessages_brake__myCar_Driver_Automatic_calc;
   float32 resources_CarMessages_power__myCar_Driver_Automatic_calc;
   uint16 resources_CarMessages_v__myCar_Driver_Automatic_calc;
   float32 resources_CarMessages_x__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_emergency__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_laneChange_left__myCar_Driver_Automatic_calc;
   boolean resources_DriverMessages_laneChange_right__myCar_Driver_Automatic_calc;
   uint16 resources_DriverMessages_v_target__myCar_Driver_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_brake__myCar_Driver_Automatic_calc = resources_CarMessages_brake;
      resources_CarMessages_power__myCar_Driver_Automatic_calc = resources_CarMessages_power;
      resources_CarMessages_v__myCar_Driver_Automatic_calc = resources_CarMessages_v;
      resources_CarMessages_x__myCar_Driver_Automatic_calc = resources_CarMessages_x;
      resources_DriverMessages_emergency__myCar_Driver_Automatic_calc = resources_DriverMessages_emergency;
      resources_DriverMessages_laneChange_left__myCar_Driver_Automatic_calc = resources_DriverMessages_laneChange_left;
      resources_DriverMessages_laneChange_right__myCar_Driver_Automatic_calc = resources_DriverMessages_laneChange_right;
      resources_DriverMessages_v_target__myCar_Driver_Automatic_calc = resources_DriverMessages_v_target;
      EnableAllInterrupts();
   }
   _cov_statement_(36U);
   distance_next_Obstacle_VAL
      = myCar_Obstacles_Automatic_distance(Obstacles_instance_REF, resources_CarMessages_x__myCar_Driver_Automatic_calc, v_target_VAL);
   _cov_statement_(37U);
   if (_cov_binary_branch_(3U, distance_next_Obstacle_VAL < min_dist_to_obstacle_VAL))
   {
      _cov_statement_(38U);
      resources_DriverMessages_emergency__myCar_Driver_Automatic_calc = true;
   }
   else
   {
      _cov_statement_(39U);
      resources_DriverMessages_emergency__myCar_Driver_Automatic_calc = false;
   } /* end if */
   _cov_statement_(40U);
   myCar_Driver_Tempo_Automatic_calc(Driver_Tempo_instance_REF, resources_CarMessages_v__myCar_Driver_Automatic_calc, v_target_VAL);
   _cov_statement_(41U);
   resources_CarMessages_brake__myCar_Driver_Automatic_calc = myCar_Driver_RAM.Driver_Tempo_instance.brake_out;
   _cov_statement_(42U);
   resources_CarMessages_power__myCar_Driver_Automatic_calc = myCar_Driver_RAM.Driver_Tempo_instance.power_out;
   _cov_statement_(43U);
   resources_DriverMessages_v_target__myCar_Driver_Automatic_calc = v_target_VAL;
   _cov_statement_(44U);
   resources_DriverMessages_laneChange_right__myCar_Driver_Automatic_calc = Lane_Change_right_VAL;
   _cov_statement_(45U);
   resources_DriverMessages_laneChange_left__myCar_Driver_Automatic_calc = Lane_Change_left_VAL;
   _cov_statement_(46U);
   min_dist_to_obstacle_VAL = myCar_Driver_RAM.Obstacles_instance.min_dist_to_obst;
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_brake = resources_CarMessages_brake__myCar_Driver_Automatic_calc;
      resources_CarMessages_power = resources_CarMessages_power__myCar_Driver_Automatic_calc;
      resources_DriverMessages_emergency = resources_DriverMessages_emergency__myCar_Driver_Automatic_calc;
      resources_DriverMessages_laneChange_left = resources_DriverMessages_laneChange_left__myCar_Driver_Automatic_calc;
      resources_DriverMessages_laneChange_right = resources_DriverMessages_laneChange_right__myCar_Driver_Automatic_calc;
      resources_DriverMessages_v_target = resources_DriverMessages_v_target__myCar_Driver_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



