/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MYCAR_DRIVER_AUTOMATIC_H_
#define _ASD_MYCAR_DRIVER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 4))
# error NOT COMPLIANT (< compliance level 4) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT {
   float32 power;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'myCar_Driver_Automatic'
 ******************************************************************************/


/* component structure for module MYCAR_DRIVER_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....................myCar_Driver_Automatic */
#define _myCar_Driver_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'myCar_Driver_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT myCar_Driver_CAL_MEM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module myCar_Driver_Automatic
 ******************************************************************************/
extern void myCar_Driver_Automatic_calc (void);



#endif /* _ASD_MYCAR_DRIVER_AUTOMATIC_H_ */
