/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................myCar.myCar
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE
#define ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define myVehicle_VAL myCar_myCar.myVehicle
#define myVehicle_REF &(myCar_myCar.myVehicle)
#define time_VAL myCar_myCar_RAM.time
#define g_VAL myCar_myCar_CAL_MEM.g
#define Landscape_VAL myCar_myCar_CAL_MEM.Landscape
#define Landscape_REF &(myCar_myCar_CAL_MEM.Landscape)
#define TrackSize_VAL myCar_myCar_CAL_MEM.TrackSize
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_MYCAR_MYCAR_AUTOMATIC_PRIVATE */

