/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................myCar.Driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "myCar_Driver_Automatic.h"
#include "resources_CarMessages_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'myCar_Driver'
 * data set:.....................................'MYCAR_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct myCar_Driver_Automatic_CAL_MEM_SUBSTRUCT myCar_Driver_CAL_MEM = {
   /* struct element:'myCar_Driver_CAL_MEM.power' (modeled as:'power.myCar_Driver') */
   10.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'myCar_Driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'myCar_Driver'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define power_VAL (myCar_Driver_CAL_MEM.power)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void myCar_Driver_Automatic_calc (void)
{
   /* define local message copies */
   float32 resources_CarMessages_power__myCar_Driver_Automatic_calc;
   /* receive messages implicitly */
   {
      resources_CarMessages_power__myCar_Driver_Automatic_calc = resources_CarMessages_power;
   }
   resources_CarMessages_power__myCar_Driver_Automatic_calc = power_VAL;
   /* send messages implicitly */
   {
      resources_CarMessages_power = resources_CarMessages_power__myCar_Driver_Automatic_calc;
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'myCar_Driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



