/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................resources.CarMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE
#define ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define resources_CarMessages_v_VAL resources_CarMessages_v
#define resources_CarMessages_power_VAL resources_CarMessages_power
#define resources_CarMessages_brake_VAL resources_CarMessages_brake
#define resources_CarMessages_steering_VAL resources_CarMessages_steering
#define resources_CarMessages_bearing_VAL resources_CarMessages_bearing
#define resources_CarMessages_x_VAL resources_CarMessages_x
#define resources_CarMessages_y_VAL resources_CarMessages_y
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_RESOURCES_CARMESSAGES_AUTOMATIC_PRIVATE */

