/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.6.0
 * CODE GENERATOR:..............V7.6.0
 * COMPONENT:...................SystemLib.Math.MathLib
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    MathLib is a C code class that returns the results of numerous mathematical functions.
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_MATH_MATHLIB_AUTOMATIC_H_
#define _ASD_SYSTEMLIB_MATH_MATHLIB_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 4))
# error NOT COMPLIANT (< compliance level 4) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for class SYSTEMLIB_MATH_MATHLIB_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........SystemLib_Math_MathLib_Automatic */
#define _SystemLib_Math_MathLib_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class SystemLib_Math_MathLib_Automatic
 ******************************************************************************/
#if !defined(SUPPRESS_SRV_FUNCTION_DECLARATION) && !defined(SystemLib_Math_MathLib_Automatic_SUPPRESS_FUNCTION_DECLARATION)
extern float64 acos (/* IN    */ const float64 val);
extern float64 asin (/* IN    */ const float64 val);
extern float64 atan (/* IN    */ const float64 val);
extern float64 atan2 (
   /* IN    */ const float64 x,
   /* IN    */ const float64 y
   );
extern float64 ceil (/* IN    */ const float64 val);
extern float64 cos (/* IN    */ const float64 val);
extern float64 cosh (/* IN    */ const float64 val);
extern float64 exp (/* IN    */ const float64 val);
extern float64 floor (/* IN    */ const float64 val);
extern float64 log (/* IN    */ const float64 val);
extern float64 log10 (/* IN    */ const float64 val);
extern float64 pow (
   /* IN    */ const float64 val,
   /* IN    */ const float64 factor
   );
extern float64 sin (/* IN    */ const float64 val);
extern float64 sinh (/* IN    */ const float64 val);
extern float64 sqrt (/* IN    */ const float64 val);
extern float64 tan (/* IN    */ const float64 val);
extern float64 tanh (/* IN    */ const float64 val);
#endif



#endif /* _ASD_SYSTEMLIB_MATH_MATHLIB_AUTOMATIC_H_ */
